/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScalesRouteImport } from './routes/scales'
import { Route as FreeplayRouteImport } from './routes/freeplay'
import { Route as CircleRouteImport } from './routes/circle'
import { Route as AnalyzerRouteImport } from './routes/analyzer'
import { Route as IndexRouteImport } from './routes/index'

const ScalesRoute = ScalesRouteImport.update({
  id: '/scales',
  path: '/scales',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeplayRoute = FreeplayRouteImport.update({
  id: '/freeplay',
  path: '/freeplay',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleRoute = CircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzerRoute = AnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/circle': typeof CircleRoute
  '/freeplay': typeof FreeplayRoute
  '/scales': typeof ScalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/circle': typeof CircleRoute
  '/freeplay': typeof FreeplayRoute
  '/scales': typeof ScalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/circle': typeof CircleRoute
  '/freeplay': typeof FreeplayRoute
  '/scales': typeof ScalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analyzer' | '/circle' | '/freeplay' | '/scales'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analyzer' | '/circle' | '/freeplay' | '/scales'
  id: '__root__' | '/' | '/analyzer' | '/circle' | '/freeplay' | '/scales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzerRoute: typeof AnalyzerRoute
  CircleRoute: typeof CircleRoute
  FreeplayRoute: typeof FreeplayRoute
  ScalesRoute: typeof ScalesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scales': {
      id: '/scales'
      path: '/scales'
      fullPath: '/scales'
      preLoaderRoute: typeof ScalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freeplay': {
      id: '/freeplay'
      path: '/freeplay'
      fullPath: '/freeplay'
      preLoaderRoute: typeof FreeplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle': {
      id: '/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof CircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzer': {
      id: '/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof AnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzerRoute: AnalyzerRoute,
  CircleRoute: CircleRoute,
  FreeplayRoute: FreeplayRoute,
  ScalesRoute: ScalesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
